### ISSUE TITLE
IndexError: index out of range

### ISSUE THREAD

**Issue by d2dyno** [JohnDoee/autotorrent#15]
Not sure what is causing this, but I'm getting this on some .torrent files:
```
Traceback (most recent call last):
  File "/usr/bin/autotorrent", line 11, in <module>
    load_entry_point('autotorrent==1.6.2', 'console_scripts', 'autotorrent')()
  File "/usr/lib64/python3.6/site-packages/autotorrent/cmd.py", line 214, in commandline_handler
    result = at.handle_torrentfile(os.path.join(current_path, torrent), dry_run)
  File "/usr/lib64/python3.6/site-packages/autotorrent/at.py", line 419, in handle_torrentfile
    torrent = self.open_torrentfile(path)
  File "/usr/lib64/python3.6/site-packages/autotorrent/at.py", line 484, in open_torrentfile
    return bdecode(f.read())
  File "/usr/lib64/python3.6/site-packages/autotorrent/bencode.py", line 62, in bdecode
    r, l = decode_func[six.indexbytes(x, 0)](x, 0)
IndexError: index out of range
```

**Comment by d2dyno** [comment]
This was an issue with corrupt .torrent files.

**Comment by JohnDoee** [comment]
We can turn this ticket into "better error on corrupt torrent"?

Errors like these can be confusing for a user yet easy for me to detect and inform about.
