### ISSUE TITLE
Can't build database

### ISSUE THREAD

**Issue by mpk99** [JohnDoee/autotorrent#20]
I can't build my initial database -- i get this error:

```python

autotorrent-env/bin/autotorrent -r


Rebuilding database
Traceback (most recent call last):
  File "autotorrent-env/bin/autotorrent", line 11, in <module>
    sys.exit(commandline_handler())
  File "/home/user/temp/autotorrent-env/lib/python3.5/site-packages/autotorrent/cmd.py", line 197, in commandline_handler
    db.rebuild()
  File "/home/user/temp/autotorrent-env/lib/python3.5/site-packages/autotorrent/db.py", line 163, in rebuild
    self.insert_into_database(root, f, 'exact', 'f')
  File "/home/user/temp/autotorrent-env/lib/python3.5/site-packages/autotorrent/db.py", line 49, in insert_into_database
    self._insert_into_database(root, f, mode, prefix, unsplitable_name)
  File "/home/user/temp/autotorrent-env/lib/python3.5/site-packages/autotorrent/db.py", line 63, in _insert_into_database
    key = self.keyify(prefix, f)
  File "/home/user/temp/autotorrent-env/lib/python3.5/site-packages/autotorrent/db.py", line 282, in keyify
    return hashlib.sha256(key.encode('utf-8')).hexdigest()
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce9' in position 6: surrogates not allowed`

**Comment by d2dyno** [comment]
I had similar issues here: https://github.com/JohnDoee/autotorrent/issues/21 which turned out to be bad folder names/not supported encoding for the name.

**Comment by sachk** [comment]
I've also had this previously. Ignoring folders with invalid characters should work for now.

**Comment by impo** [comment]
> I've also had this previously. Ignoring folders with invalid characters should work for now.

How would I do that?

**Comment by JohnDoee** [comment]
Thanks for reporting this.

This is folded into #45
