### ISSUE TITLE
IOError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by adamwinn** [JohnDoee/autotorrent#34]
```
Traceback (most recent call last):
  File "cmd.py", line 288, in <module>
    commandline_handler()
  File "cmd.py", line 214, in commandline_handler
    result = at.handle_torrentfile(os.path.join(current_path, torrent_file), dry_run)
  File "/usr/lib/python2.7/site-packages/autotorrent-1.7.0-py2.7.egg/autotorrent/at.py", line 428, in handle_torrentfile
    found_size, missing_size, files = self.parse_torrent(torrent)
  File "/usr/lib/python2.7/site-packages/autotorrent-1.7.0-py2.7.egg/autotorrent/at.py", line 319, in parse_torrent
    files = self.index_torrent(torrent)
  File "/usr/lib/python2.7/site-packages/autotorrent-1.7.0-py2.7.egg/autotorrent/at.py", line 308, in index_torrent
    modified_result, result = self.find_hash_checks(torrent, result)
  File "/usr/lib/python2.7/site-packages/autotorrent-1.7.0-py2.7.egg/autotorrent/at.py", line 138, in find_hash_checks
    match_start, match_end = pieces.match_file(db_file, start_size, end_size)
  File "/usr/lib/python2.7/site-packages/autotorrent-1.7.0-py2.7.egg/autotorrent/utils.py", line 159, in match_file
    f.seek(seek_offset)
IOError: [Errno 22] Invalid argument
```

**Comment by matemoln** [comment]
Got this error on file: DJ KÃ¼sse & .....torrent

**Comment by JohnDoee** [comment]
@matemoln also on f.seek ? Feels like that'd be on a filesystem that does not support.

**Comment by matemoln** [comment]
`$ autotorrent -a torrents/DJ_K++sse_and_Khshathra....torrent`
```
Found 1 torrent(s)
Traceback (most recent call last):
  File "/home/mate/.local/bin/autotorrent", line 10, in <module>
    sys.exit(commandline_handler())
  File "/home/mate/.local/lib/python2.7/site-packages/autotorrent/cmd.py", line 210, in commandline_handler
    result = at.handle_torrentfile(os.path.join(current_path, torrent), dry_run)
  File "/home/mate/.local/lib/python2.7/site-packages/autotorrent/at.py", line 428, in handle_torrentfile
    found_size, missing_size, files = self.parse_torrent(torrent)
  File "/home/mate/.local/lib/python2.7/site-packages/autotorrent/at.py", line 319, in parse_torrent
    files = self.index_torrent(torrent)
  File "/home/mate/.local/lib/python2.7/site-packages/autotorrent/at.py", line 308, in index_torrent
    modified_result, result = self.find_hash_checks(torrent, result)
  File "/home/mate/.local/lib/python2.7/site-packages/autotorrent/at.py", line 138, in find_hash_checks
    match_start, match_end = pieces.match_file(db_file, start_size, end_size)
  File "/home/mate/.local/lib/python2.7/site-packages/autotorrent/utils.py", line 159, in match_file
    f.seek(seek_offset)
IOError: [Errno 22] Invalid argument
```

**Comment by awcip** [comment]
I solved this problem by removing `hash_name` from `scan_mode` in my `.conf`. I have no idea why it works.
