### ISSUE TITLE
qbittorrent 4.2 login error

### ISSUE THREAD

**Issue by d2dyno** [JohnDoee/autotorrent#36]
```
Traceback (most recent call last):
  File "/usr/bin/autotorrent", line 11, in <module>
    load_entry_point('autotorrent==1.7.0', 'console_scripts', 'autotorrent')()
  File "/usr/lib64/python3.6/site-packages/autotorrent/cmd.py", line 207, in commandline_handler
    at.populate_torrents_seeded()
  File "/usr/lib64/python3.6/site-packages/autotorrent/at.py", line 84, in populate_torrents_seeded
    self.torrents_seeded = set(x.lower() for x in self.client.get_torrents())
  File "/usr/lib64/python3.6/site-packages/autotorrent/clients/qbittorrent.py", line 79, in get_torrents
    self._login_check()
  File "/usr/lib64/python3.6/site-packages/autotorrent/clients/qbittorrent.py", line 45, in _login_check
    raise UnableToLoginException()
autotorrent.clients.qbittorrent.UnableToLoginException
```

**Comment by JohnDoee** [comment]
Thanks! Should be fixed in 1.7.1, not sure how I missed this originally.
