### ISSUE TITLE
Move to Python 3 only and solve the encoding problems.

### ISSUE THREAD

**Issue by JohnDoee** [JohnDoee/autotorrent#45]
Part of the unicode problems stem from still having Python 2 support, this issue is all those issues folded into one.

Related issues: #16 #20 #35 #42 

- [ ] Move to pathlib
- [ ] Move from shelve to sqlite as internal database

**Comment by awcip** [comment]
Is there any progress on this? I am having trouble adding some files which seem to stem from some encoding issue since vs-code complains that the particular file has an binary or unknown encoding compared to some files which do work.

```
Traceback (most recent call last):
  File "/autotorrent-env/bin/autotorrent", line 8, in <module>
    sys.exit(commandline_handler())
  File "/autotorrent-env/lib/python3.6/site-packages/autotorrent/cmd.py", line 210, in commandline_handler
    result = at.handle_torrentfile(os.path.join(current_path, torrent), dry_run)
  File "/autotorrent-env/lib/python3.6/site-packages/autotorrent/at.py", line 428, in handle_torrentfile
    found_size, missing_size, files = self.parse_torrent(torrent)
  File "/autotorrent-env/lib/python3.6/site-packages/autotorrent/at.py", line 319, in parse_torrent
    files = self.index_torrent(torrent)
  File "/autotorrent-env/lib/python3.6/site-packages/autotorrent/at.py", line 308, in index_torrent
    modified_result, result = self.find_hash_checks(torrent, result)
  File "/autotorrent-env/lib/python3.6/site-packages/autotorrent/at.py", line 138, in find_hash_checks
    match_start, match_end = pieces.match_file(db_file, start_size, end_size)
  File "/autotorrent-env/lib/python3.6/site-packages/autotorrent/utils.py", line 159, in match_file
    f.seek(seek_offset)
```

**Comment by HarringtonTom** [comment]
I'm also having the same problem.
