### ISSUE TITLE
Error building Database with NTFS drive.

### ISSUE THREAD

**Issue by b0xy** [JohnDoee/autotorrent#6]
scan error's out when hitting system volume.

Traceback (most recent call last):
  File "./autotorrent", line 11, in <module>
    sys.exit(commandline_handler())
  File "/home/mgmt/autotorrent-env/local/lib/python2.7/site-packages/autotorrent/cmd.py", line 113, in commandline_handler
    db.rebuild()
  File "/home/mgmt/autotorrent-env/local/lib/python2.7/site-packages/autotorrent/db.py", line 156, in rebuild
    self.insert_into_database(root, f, 'normal')
  File "/home/mgmt/autotorrent-env/local/lib/python2.7/site-packages/autotorrent/db.py", line 49, in insert_into_database
    self._insert_into_database(root, f, mode, prefix, unsplitable_name)
  File "/home/mgmt/autotorrent-env/local/lib/python2.7/site-packages/autotorrent/db.py", line 67, in _insert_into_database
    size = os.path.getsize(path)
  File "/home/mgmt/autotorrent-env/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 13] Permission denied: '/mnt/hgfs/D/System Volume Information'

**Comment by JohnDoee** [comment]
I've added a check to make sure files are accessible when rebuilding.

I do not have a setup that allows for easy testing and it seems like it is handled a bit differently directly on ext4. Anyways, pushed a fix to develop branch.

**Comment by b0xy** [comment]
pulled from dev branch, testing.

**Comment by JohnDoee** [comment]
Super, thanks for reporting it :+1:
